name: finance-vibe

services:
  finance-vibe:
    container_name: finance_vibe

    build:
      context: .

    ports:
      - "5000:5000"

    volumes:
      - ./data:/app/data

    restart: unless-stopped

    environment:
      TZ: America/New_York
      FLASK_DEBUG: "0"
