#!/usr/bin/env bash
# Clean out the Finance Vibe data volume (raw OHLCV and/or scan logs).
#
# Usage:
#   scripts/clean_data_volume.sh [--target raw|logs|all] [--data-dir PATH]
#                                 [--dry-run] [--yes] [--docker-cache]
#
# Targets:
#   raw   - data/raw/{weekly,daily}/*.csv   (safe: regenerated by the next
#           data_ingestor.py run; this is what run_vibe.py itself wipes
#           before every ingest unless --reuse-raw is passed)
#   logs  - data/logs/{weekly,daily,high_beta}/*.csv  (DESTRUCTIVE: scan
#           results, trade plans, and backtest archives are not
#           regenerated -- only delete these if you don't need the history)
#   all   - both of the above (default)
#
# Data directory resolution (first match wins), unless --data-dir is given:
#   1. /mnt/fast/finance-vibe-data   (the docker-compose bind mount)
#   2. <repo_root>/data              (local/dev run, matches config.py)
#
# Examples:
#   scripts/clean_data_volume.sh --dry-run              # preview, no changes
#   scripts/clean_data_volume.sh --target raw --yes      # wipe raw only, no prompt
#   scripts/clean_data_volume.sh                         # wipe raw+logs, prompts first
#   scripts/clean_data_volume.sh --docker-cache          # also prune docker build cache
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

TARGET="all"
DATA_DIR=""
DRY_RUN=0
ASSUME_YES=0
CLEAN_DOCKER_CACHE=0

usage() {
    sed -n '2,24p' "${BASH_SOURCE[0]}"
    exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --target)
            TARGET="${2:?--target needs a value: raw|logs|all}"
            shift 2
            ;;
        --data-dir)
            DATA_DIR="${2:?--data-dir needs a path}"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=1
            shift
            ;;
        --yes|-y)
            ASSUME_YES=1
            shift
            ;;
        --docker-cache)
            CLEAN_DOCKER_CACHE=1
            shift
            ;;
        -h|--help)
            usage 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage 1
            ;;
    esac
done

case "$TARGET" in
    raw|logs|all) ;;
    *)
        echo "Invalid --target '$TARGET' (expected raw, logs, or all)" >&2
        exit 1
        ;;
esac

if [[ -z "$DATA_DIR" ]]; then
    if [[ -d "/mnt/fast/finance-vibe-data" ]]; then
        DATA_DIR="/mnt/fast/finance-vibe-data"
    else
        DATA_DIR="$REPO_ROOT/data"
    fi
fi

if [[ ! -d "$DATA_DIR" ]]; then
    echo "Data directory does not exist: $DATA_DIR" >&2
    exit 1
fi

RAW_DIRS=("$DATA_DIR/raw/weekly" "$DATA_DIR/raw/daily")
LOG_DIRS=("$DATA_DIR/logs/weekly" "$DATA_DIR/logs/daily" "$DATA_DIR/logs/high_beta")

collect_files() {
    local dirs=("$@")
    local d
    for d in "${dirs[@]}"; do
        [[ -d "$d" ]] || continue
        find "$d" -maxdepth 1 -type f -name '*.csv'
    done
}

FILES_TO_DELETE=()
if [[ "$TARGET" == "raw" || "$TARGET" == "all" ]]; then
    while IFS= read -r f; do
        [[ -n "$f" ]] && FILES_TO_DELETE+=("$f")
    done < <(collect_files "${RAW_DIRS[@]}")
fi
if [[ "$TARGET" == "logs" || "$TARGET" == "all" ]]; then
    while IFS= read -r f; do
        [[ -n "$f" ]] && FILES_TO_DELETE+=("$f")
    done < <(collect_files "${LOG_DIRS[@]}")
fi

echo "Data directory: $DATA_DIR"
echo "Target:         $TARGET"
echo "Files matched:  ${#FILES_TO_DELETE[@]}"

if [[ ${#FILES_TO_DELETE[@]} -eq 0 ]]; then
    echo "Nothing to clean."
else
    printf '  %s\n' "${FILES_TO_DELETE[@]}"
fi

if [[ "$TARGET" == "logs" || "$TARGET" == "all" ]]; then
    echo
    echo "NOTE: 'logs' contains scan results, trade plans, and backtest"
    echo "archives that are NOT regenerated automatically -- only proceed"
    echo "if you don't need that history."
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
    echo
    echo "(dry run -- nothing deleted)"
elif [[ ${#FILES_TO_DELETE[@]} -gt 0 ]]; then
    if [[ "$ASSUME_YES" -ne 1 ]]; then
        echo
        read -r -p "Delete ${#FILES_TO_DELETE[@]} file(s) above? [y/N] " reply
        case "$reply" in
            [yY]|[yY][eE][sS]) ;;
            *) echo "Aborted."; exit 1 ;;
        esac
    fi
    for f in "${FILES_TO_DELETE[@]}"; do
        rm -f -- "$f"
    done
    echo "Deleted ${#FILES_TO_DELETE[@]} file(s)."
fi

if [[ "$CLEAN_DOCKER_CACHE" -eq 1 ]]; then
    if ! command -v docker >/dev/null 2>&1; then
        echo "docker not found on PATH; skipping --docker-cache." >&2
    elif [[ "$DRY_RUN" -eq 1 ]]; then
        echo
        echo "Docker disk usage (dry run -- would prune build cache):"
        docker system df
    else
        echo
        echo "Pruning docker build cache..."
        docker builder prune -f
    fi
fi
